---
- hosts: lb
  roles:
    - { role: /home/ubuntu/ansible-config/roles/nginxRole, when: enable_nginx_lb and load_balancer_is_required }
    - { role: /home/ubuntu/ansible-config/roles/apacheRole, when: enable_apache_lb and load_balancer_is_required }
  become: yes  
