[nfs]
172.31.30.187 ansible_ssh_user='ec2-user'

[webservers]
172.31.26.195 ansible_ssh_user='ec2-user'
172.31.18.150 ansible_ssh_user='ec2-user'

[db]
172.31.40.171 ansible_ssh_user='ec2-user' 

[lb]
172.31.45.62 ansible_ssh_user='ubuntu'
